using Bogus;
using Microsoft.EntityFrameworkCore;
using SupplyChainManagementSystem.Server.Models;

namespace SupplyChainManagementSystem.DataAccess
{
    public class ProductDbContext : DbContext
    {
        private readonly IConfiguration _configuration;

        public ProductDbContext(DbContextOptions<ProductDbContext> options, IConfiguration configuration) : base(options)
        {
            _configuration = configuration;
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
        }

        public DbSet<Product> Products { get; set; } = default!;

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Product>().ToTable("Product");

            modelBuilder.Entity<Product>().HasKey(p => p.Product_Id);

            var products = GenerateProductData();

            modelBuilder.Entity<Product>().HasData(products);
        }

        private static Product[] GenerateProductData()
        {
            var productFaker = new Faker<Product>()
                .RuleFor(p => p.Product_Id, f => Guid.NewGuid())
                .RuleFor(p => p.Product_Name, f => f.Commerce.ProductName())
                .RuleFor(p => p.Product_Description, f => f.Lorem.Sentence(10)) // Kanjilal code had this f.Commerce.ProductDescription()
                .RuleFor(p => p.Product_Category, f => f.Commerce.Categories(1)[0]) // Kanjilal code had this f.Commerce.ProductMaterial()
                .RuleFor(p => p.Product_Price, f => decimal.Parse(f.Commerce.Price(1000, 5000)))    // Kanjilal code had this f.Random.Decimal(1000, 5000), 2)
                .RuleFor(p => p.Product_Quantity, f => f.Random.Int(1, 100))    // Kanjilal code didn't have anything for Product_Quantity
                .RuleFor(p => p.Created_At, f => DateTime.Now); // Technically, this isn't necessary, as it is generated by the class instantiation

            return productFaker.Generate(count: 5).ToArray();
        }
    }

}
